export const UPDATE_ROLE_FILTER = "UPDATE_ROLE_FILTER";
export const UPDATE_EXPERIENCE_FILTER = "UPDATE_EXPERIENCE_FILTER";
export const UPDATE_STACK_FILTER = "UPDATE_STACK_FILTER";
export const UPDATE_LOCATION_FILTER = "UPDATE_LOCATION_FILTER";
export const UPDATE_COMPANY_FILTER = "UPDATE_COMPANY_FILTER";
export const UPDATE_SALARY_FILTER = "UPDATE_SALARY_FILTER";
export const UPDATE_JOB_TYPE_FILTER = "UPDATE_JOB_TYPE_FILTER";
